version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "4040:4000"
    env_file: ./env/dev.env
    command: bash scripts/dev.sh
    volumes:
      - .:/home/app/service/
